OBJS += passes/hw_sw_contracts/dump_list_of_wires.o
OBJS += passes/hw_sw_contracts/and_of_multiple_wires.o
OBJS += passes/hw_sw_contracts/add_equality_contraint.o
OBJS += passes/hw_sw_contracts/preserve_past_values.o
OBJS += passes/hw_sw_contracts/add_bitwise_negation.o
OBJS += passes/hw_sw_contracts/create_product_circuit.o